{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0').lstrip('v') %}

package:
  name: pyomp
  version: {{ version }}

source:
   path: ../../..

build:
  string: py{{ PY_VER }}h{{ PKG_HASH }}_{{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PY_VCRUNTIME_REDIST # [win]
  script:
    - export VERBOSE=1
    - export CPPFLAGS="-mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET} -isystem ${PREFIX}/include -D_FORTIFY_SOURCE=2" # [osx]
    - rm -rf build dist src/numba/openmp/libs src/*.egg-info
    - {{ PYTHON }} -m pip install -v .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - setuptools_scm
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - numba >=0.57, <0.59
    - llvmdev 14.*
  run:
    - python
    - setuptools
    - numba >=0.57, <0.59
    - lark
    - cffi

about:
  home: https://github.com/Python-for-HPC/PyOMP
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "PyOMP: OpenMP for portable CPU/GPU parallel programming in Python using Numba."
