{% set version = environ.get('GIT_DESCRIBE_TAG', '0.0.0').lstrip('v') %}
{% set LLVM_VERSION = environ.get('LLVM_VERSION', '20.1.8') %}

package:
  name: pyomp
  version: {{ version }}

source:
   path: ../../..

build:
  string: py{{ PY_VER }}h{{ PKG_HASH }}_{{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PY_VCRUNTIME_REDIST # [win]
  script:
    - export LLVM_VERSION={{ LLVM_VERSION }}
    - export LLVM_DIR=${PREFIX}
    - export CC=${PREFIX}/bin/clang
    - export CXX=${PREFIX}/bin/clang++
    - export VERBOSE=1
    - export CPPFLAGS="-mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET} -isystem ${PREFIX}/include -D_FORTIFY_SOURCE=2" # [osx]
    - export ENABLE_BUNDLED_LIBOMPTARGET=1 # [linux]
    - rm -rf build dist src/*.egg-info
    - {{ PYTHON }} -m pip install -v .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Add sysroot to ensure compatibility on linux builds.
    - sysroot_linux-64       # [linux64]
    - sysroot_linux-aarch64  # [aarch64]
    - cmake
    - ninja
    - setuptools_scm
    - elfutils # [linux]
    - libffi # [linux]
  host:
    - python
    - pip
    # Add sysroot to ensure compatibility on linux builds.
    - sysroot_linux-64       # [linux64]
    - sysroot_linux-aarch64  # [aarch64]
    - setuptools
    - setuptools_scm
    - numba >=0.62, <0.64
    - clang {{ LLVM_VERSION }}
    - clangxx {{ LLVM_VERSION }}
    - clang-tools {{ LLVM_VERSION }}
    - llvmdev {{ LLVM_VERSION }}
    - zlib
    # require llvm-openmp for the openmp cpu runtime.
    - llvm-openmp {{ LLVM_VERSION }}
    - elfutils # [linux]
    - libffi # [linux]
  run:
    - python
    - setuptools
    - numba >=0.62, <0.64
    # require llvm-openmp for the openmp cpu runtime.
    - llvm-openmp {{ LLVM_VERSION }}
    - lark
    - cffi

test:
  commands:
    - test -f $SP_DIR/numba/openmp/libs/pass/libIntrinsicsOpenMP.dylib                 # [osx]
    - test -f $SP_DIR/numba/openmp/libs/pass/libIntrinsicsOpenMP.so                    # [linux]
    - test -f $SP_DIR/numba/openmp/libs/openmp/lib/libomptarget-amdgpu.bc        # [linux]
    - test -f $SP_DIR/numba/openmp/libs/openmp/lib/libomptarget-nvptx.bc         # [linux]
    - test -f $SP_DIR/numba/openmp/libs/openmp/lib/libomptarget.so               # [linux]

about:
  home: https://github.com/Python-for-HPC/PyOMP
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "PyOMP: OpenMP for portable CPU/GPU parallel programming in Python using Numba."
