{% set version = "0.2.0" %}

package:
  name: pyomp
  version: {{ version }}

source:
   path: ../../..

build:
  string: py{{ PY_VER }}h{{ PKG_HASH }}_{{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  script_env:
    - PY_VCRUNTIME_REDIST # [win]
  script:
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - numba >=0.57, <0.58
  run:
    - numba >=0.57, <0.58
    - lark
    - cffi
    - llvm-openmp-dev

about:
  home: https://github.com/Python-for-HPC/PyOMP
  license: BSD-2-Clause
  license_file: LICENSE
  summary: "PyOMP: OpenMP for portable CPU/GPU parallel programming in Python using Numba."
