{% set version = "2019.3" %} # this is the intel version to get
{% set win_build_number = "203" %}   # the build number from the intel windows version
{% set osx_build_number = "199" %}   # the build number from the intel osx version
{% set lnx_build_number = "199" %}   # the build number from the intel linux version

package:
  name: icc_rt
  version: {{ version }}

build:
  number: {{ win_build_number }}  # [win]
  number: {{ osx_build_number }}  # [osx]
  number: {{ lnx_build_number }}  # [linux]

source:
    - url: https://anaconda.org/intel/icc_rt/{{ version }}/download/win-64/icc_rt-{{version}}-intel_{{win_build_number}}.tar.bz2 # [win]
    - md5: d39bae3218457a4ea045763fdcfc1562 # [win]
    - sha256: 2c55b8af1dea35ee4648b671050899a93b7eba1b26acad019bf569ca777a944e # [win]

    - url: https://anaconda.org/intel/icc_rt/{{ version }}/download/osx-64/icc_rt-{{version}}-intel_{{osx_build_number}}.tar.bz2 # [osx]
    - md5: 064566ac53e729d3f008e32b1f73d1fa # [osx]
    - sha256: 54a372b0d8d5b4d750c28ea122851b52ec9aa3cccb8d4cf4a2999494dfda6656 # [osx]

    - url: https://anaconda.org/intel/icc_rt/{{ version }}/download/linux-64/icc_rt-{{version}}-intel_{{lnx_build_number}}.tar.bz2 # [linux]
    - md5: 306c3ee9491577715dbd76c838147078 # [linux]
    - sha256: 4cedd10343d1ab4403af2ff080b47afe5399be550f1c215e5a7c7eceec672516 # [linux]

    - path: scripts

requirements:
  build:
    - python>=3

about:
  license: "Intel"
  license_family: "Proprietary"
  license_file: LICENSE.txt
summary: Intel ICC runtime.
