{% set version = "pyomp_0.57" %}

package:
   name: numba
   #version: {{ GIT_DESCRIBE_TAG }}
   version: {{ version }}

source:
  git_url: https://github.com/Python-for-HPC/numbaWithOpenmp.git
  git_rev: develop
  git_depth: 1

build:
  string: np{{ NPY_VER }}py{{ PY_VER }}h{{ PKG_HASH }}_{{ version }}_{{ (GITHUB_HEAD_SHA | default(''))[:7] ~ (CI_COMMIT_SHA | default(''))[:7] }}
  entry_points:
    - numba = numba.misc.numba_entry:main
  script_env:
    - PY_VCRUNTIME_REDIST
    - GITHUB_HEAD_SHA
    - CI_COMMIT_SHA
  missing_dso_whitelist: # [osx]
    # optional dependency: required only when omp is chosen as the backend for
    # the threading layer
    - lib/libiomp5.dylib # [osx]
  #ignore_run_exports:
    # tbb-devel triggers hard dependency on tbb, this is not the case.
    - tbb     # [not (aarch64 or ppc64le or win32)]

requirements:
  # build and run dependencies are duplicated to avoid setuptools issues
  # when we also set install_requires in setup.py
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # OpenMP headers from llvm needed for OSX.
  host:
    - python
    - numpy >=1.22.3, <1.25
    - llvm-openmp-dev
    - setuptools
    - importlib_metadata       # [py<39]
    - llvmlite pyomp_0.40.*
    # TBB devel version is to match TBB libs.
    # NOTE: ppc64le and aarch64 are pending testing so excluded for now, win32
    # is not a supported parallel target.
    - tbb-devel >=2021.6       # [not (aarch64 or ppc64le or win32)]
  run:
    - python
    # NumPy 1.22.0, 1.22.1, 1.22.2 are all broken for ufuncs, see #7756
    - numpy >=1.22.3, <1.25
    - importlib_metadata       # [py<39]
    # On channel https://anaconda.org/numba/
    - llvmlite pyomp_0.40.*
    - lark-parser
    - cffi
    - llvm-openmp-dev
  run_constrained:
    # If TBB is present it must be at least version 2021.6
    - tbb >=2021.6    # [not (aarch64 or ppc64le or win32)]
    # avoid confusion from openblas bugs
    - libopenblas !=0.3.6      # [x86_64]
    # 0.3.17 buggy on M1 silicon
    # https://github.com/xianyi/OpenBLAS/blob/v0.3.20/Changelog.txt#L118
    # https://github.com/numba/numba/issues/7822#issuecomment-1063229855
    # Exclude 0.3.20 too
    # https://github.com/numba/numba/issues/8096
    - libopenblas >=0.3.18, !=0.3.20     # [arm64]
    # CUDA 10.2 or later is required for CUDA support
    - cudatoolkit >=10.2
    # scipy 1.0 or later
    - scipy >=1.0
    # CUDA Python 11.6 or later
    - cuda-python >=11.6

test:
  requires:
    - jinja2
    # Required to test optional Numba features
    - cffi
    - scipy
    - ipython                  # [not aarch64]
    # for pycc
    - setuptools
    - tbb >=2021.6             # [not (aarch64 or ppc64le or win32)]
    # this is clobbering as run depends on llvm-openmp-dev
    #- llvm-openmp              # [osx]
    # This is for driving gdb tests
    - pexpect                  # [linux64]
    # For testing ipython
    - ipykernel
    # Need these for AOT. Do not init msvc as it may not be present
    - {{ compiler('c') }}      # [not (win or aarch64)]
    - {{ compiler('cxx') }}    # [not (win or aarch64)]

about:
  home: https://numba.pydata.org/
  license: BSD
  license_file: LICENSE
  summary: a just-in-time Python function compiler based on LLVM
