package:
  name: llvmlite
  version: pyomp_0.40

source:
  git_url: https://github.com/Python-for-HPC/llvmliteWithOpenmp.git
  git_rev: develop
  git_depth: 1

build:
  string: py{{ PY_VER }}h{{ PKG_HASH }}_{{ (GITHUB_HEAD_SHA | default(''))[:7] ~ (CI_COMMIT_SHA | default(''))[:7] }}
  script_env:
    - PY_VCRUNTIME_REDIST
    - GITHUB_HEAD_SHA
    - CI_COMMIT_SHA

requirements:
  build:
    # We cannot do this on macOS as the llvm-config from the
    # toolchain conflicts with the same from llvmdev, the
    # build.sh deals with it!
    - {{ compiler('c') }}    # [not (osx or armv6l or armv7l or win)]
    - {{ compiler('cxx') }}  # [not (osx or armv6l or armv7l or win)]
    # The DLL build uses cmake on Windows
    - cmake          # [win]
    - make           # [unix]
  host:
    - python
    # On channel https://anaconda.org/numba/
    - llvmdev 14.0.6
    - llvm 14.0.6
    - vs2015_runtime # [win]
    # llvmdev is built with libz compression support
    - zlib           # [unix and not (armv6l or armv7l)]
    # requires libxml2
    - libxml2        # [win]
  run:
    - python >=3.8,<=3.10
    - vs2015_runtime # [win]
    # osx has dynamically linked libstdc++
    - libcxx >=4.0.1 # [osx]

test:
  imports:
    - llvmlite
    - llvmlite.binding
  commands:
    - python -m llvmlite.tests

about:
  home: https://github.com/numba/llvmlite
  license: New BSD License
  summary: A lightweight LLVM python binding for writing JIT compilers
