
name: Build and upload conda packages

on:
  #push:
  #  paths:
  #    - 'buildscripts/conda-recipes/**'
  #    - 'llvm-project'
  #    - 'llvmliteWithOpenmp'
  #    - 'NumbaWithOpenmp'
  #pull_request:
  #  paths:
  #    - 'buildscripts/conda-recipes/**'
  #    - 'llvm-project'
  #    - 'llvmliteWithOpenmp'
  #    - 'NumbaWithOpenmp'
  workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  # Job to create llvmdev, runs once, it is independent of the python version
  # fixed at 3.10 for building.
  conda_build_llvmdev:
    name: Conda build llvmdev for platform ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macOS-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Create and activate conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          environment-file: .github/env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload the llvmdev conda package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: buildscripts/conda-recipes/llvmdev
          python-version: "3.10"
          user: python-for-hpc
          label: main
          overwrite: true
          token: ${{ secrets.ANACONDA_TOKEN }}

  # Job to create llvmlite, numba, pyomp packages.
  conda_deployment_with_new_tag:
    needs: conda_build_llvmdev
    name: Conda deployment of package for platform ${{ matrix.os }} with Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [macOS-latest, ubuntu-latest, windows-latest]
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Conda environment creation and activation
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: .github/env.yaml
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true

      - name: Build and upload the llvmlite conda package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: buildscripts/conda-recipes/llvmlite
          python-version: ${{ matrix.python-version }}
          user: python-for-hpc
          label: main
          overwrite: true
          token: ${{ secrets.ANACONDA_TOKEN }}
      - name: Build and upload the numba conda package
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: buildscripts/conda-recipes/numba
          python-version: ${{ matrix.python-version }}
          user: python-for-hpc
          label: main
          overwrite: true
          token: ${{ secrets.ANACONDA_TOKEN }}
      - name: Build and upload the pyomp conda metapackage
        uses: uibcdf/action-build-and-upload-conda-packages@v1.3.0
        with:
          meta_yaml_dir: buildscripts/conda-recipes/pyomp
          python-version: ${{ matrix.python-version }}
          user: python-for-hpc
          label: main
          overwrite: true
          token: ${{ secrets.ANACONDA_TOKEN }}
