name: Deploy conda pkgs (test)

on:
  pull_request:
    paths:
      - "buildscripts/conda-recipes/**"
      - ".github/workflows/build-upload-conda-test.yml"
      - ".github/workflows/build-upload-conda-base.yml"
      - "src/**"
      - setup.py
      - MANIFEST.in
      - pyproject.toml
  workflow_dispatch:

jobs:
  deploy-pypi:
    uses: ./.github/workflows/build-upload-pypi.yml
    with:
      label: test
    secrets: inherit
  deploy-conda:
    uses: ./.github/workflows/build-upload-conda-base.yml
    with:
      label: test
      env: .github/workflows/envs/env-test.yml
    secrets: inherit
