name: Deploy conda base

on:
  workflow_call:
    inputs:
      label:
        required: true
        type: string
      env:
        required: true
        type: string

jobs:
  # Job to deploy the pyomp metapackage matrixed on the python version.
  conda-deploy-pyomp:
    name: ${{ matrix.os }} ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: Add windows.
        os: [ubuntu-latest, macos-latest, ubuntu-24.04-arm]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
        # Checkout the repo with history to get the commit hash for the build
        # string.
        with:
          fetch-depth: 0
      - name: Create and activate conda env
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          environment-file: ${{ inputs.env }}
          auto-update-conda: false
          auto-activate-base: false
          show-channel-urls: true
      - name: Build and upload pyomp
        run: |
          # Setup the anaconda environment.
          conda remove --name base conda-anaconda-telemetry
          conda install -q -y -c conda-forge conda-build conda-verify anaconda-client
          conda config --set anaconda_upload no

          # Build the package.
          conda build \
            -c conda-forge \
            --python ${{ matrix.python-version }} \
            buildscripts/conda-recipes/pyomp

          # Get the output file path.
          OUTPUT=$(conda build -c conda-forge --output \
            --python ${{ matrix.python-version }} \
            buildscripts/conda-recipes/pyomp)

          # Upload the package.
          anaconda -t ${{ secrets.ANACONDA_TOKEN }} upload \
            --user python-for-hpc --label ${{ inputs.label }} \
            --force "$OUTPUT"
