name: Deploy pypi wheels

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # Job to deploy the pyomp metapackage matrixed on the python version.
  build-wheels:
    name: Build wheels ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: Add windows.
        os: [ubuntu-latest, macOS-latest, ubuntu-24.04-arm]
    steps:
      - uses: actions/checkout@v4
        # Checkout the repo with history to get the commit hash for the build
        # string.
        with:
          fetch-depth: 0

       # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: pypi-cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  publish-pypi:
    needs: build-wheels
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: pypi-cibw-*
          path: dist
          merge-multiple: true

      - name: Publish pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
