name: Deploy conda (main)

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy-conda:
    uses: ./.github/workflows/build-upload-conda-base.yml
    with:
      label: main
      env: .github/workflows/envs/env.yml
    secrets: inherit
  deploy-containers:
    needs: deploy-conda
    uses: ./.github/workflows/build-containers.yml
    secrets: inherit
