name: Deploy conda pkgs (test)

on:
  pull_request:
    paths:
      - "buildscripts/conda-recipes/**"
      - ".github/workflows/build-upload-conda-test.yml"
      - ".github/workflows/build-upload-conda-base.yml"
      - "numba/**"
  workflow_dispatch:

jobs:
  deploy-conda:
    uses: ./.github/workflows/build-upload-conda-base.yml
    with:
      label: test
      env: .github/workflows/envs/env-test.yml
    secrets: inherit
