name: Deploy conda pkgs (test)

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy-conda:
    uses: ./.github/workflows/build-upload-conda-base.yml
    with:
      label: test
      commit: ${{ github.event.pull_request.head.sha }}
      env: .github/workflows/envs/env-test.yml
    secrets: inherit