
name: Cross-build and upload conda packages using docker

on:
  push:
  workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  cross_conda_build_llvmdev_mac:
    name: Conda cross build with mac
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install podman
        run: |
          sysctl -n hw.ncpu
          sysctl -n hw.memsize
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew update
          brew install podman
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - name: Create machine
        run: |
          podman machine init --cpus 3 --memory 6144
          podman machine start
      - name: Run in container
        run: |
          pdoman run --rm --platform linux-aarch64 ubuntu:22.04 \
          bash -c "uname -a"
      
  ## Job to create llvmdev, runs once, it is independent of the python version
  ## fixed at 3.10 for building.
  #cross_conda_build_llvmdev:
  #  name: Conda cross build llvmdev for platform linux-aarch64
  #  runs-on: ubuntu-22.04
  #  strategy:
  #    matrix:
  #      arch: 
  #        - aarch64
  #      distro:
  #        - ubuntu:22.04
  #  steps:
  #    - uses: actions/checkout@v4
  #    - name: Setup QEMU
  #      uses: docker/setup-qemu-action@v3
  #      with:
  #        platforms: ${{ matrix.arch }}
  #    - name: Run in Docker
  #      run: |
  #        docker run \
  #          --rm \
  #          -v $(pwd):/${{ github.workspace }} \
  #          -w ${{ github.workspace }} \
  #          --platform linux/${{ matrix.arch }} \
  #          ${{ matrix.distro }} \
  #          bash -c " \
  #          apt-get -qq update &&
  #          apt-get -qq install -yq wget &&
  #          echo \"FETCH MINICONDA\" &&
  #          wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-${{ matrix.arch }}.sh -O miniconda.sh &&
  #          echo \"EXECUTE MINICONDA INSTALLATION\" &&
  #          bash miniconda.sh -b -u -p /miniconda3 &&
  #          echo \"DONE\" &&
  #          rm -rf miniconda.sh &&
  #          export PATH=/miniconda3/bin:$PATH &&
  #          conda install -yq binutils make git conda-build conda-verify &&
  #          pushd buildscripts/conda-recipes/llvmdev &&
  #          conda build -c conda-forge --override-channels .
  #          popd
  #          "